//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemsProyect.Components.Pages.Actions.Teacher.Course.Asigment
{


    public partial class Assigment
    {

        /// <summary>
        /// ButtonAddAsigment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ButtonAddAsigment;

        /// <summary>
        /// buttonAddGrade control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button buttonAddGrade;

        /// <summary>
        /// AddAsigmentControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SistemsProyect.Components.Pages.Actions.Teacher.Course.Asigment.Views.AddAsigment AddAsigmentControl;

        /// <summary>
        /// GradeAsigmentControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SistemsProyect.Components.Pages.Actions.Teacher.Course.Asigment.Views.GradeAsigment GradeAsigmentControl;

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new SistemsProyect.SiteMaster Master
        {
            get
            {
                return ((SistemsProyect.SiteMaster)(base.Master));
            }
        }
    }
}
